/* ==========================================================================
   BUILD
   Concatenates src/css/*.css → dist/sirwade.css and src/js/*.js →
   dist/sirwade.js, in filename order (hence the numeric prefixes), and
   regenerates preview.html from the blocks.

   No bundler, no dependencies, no node_modules — jsDelivr serves the dist
   files straight from the repo, so the build has to stay trivially
   inspectable.

     node build.mjs
   ========================================================================== */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));

const banner = (kind) =>
  `/*! Sir Wade — ${kind} bundle
 *  Generated by build.mjs. DO NOT EDIT THIS FILE.
 *  Edit src/${kind.toLowerCase()}/*.${kind.toLowerCase()} and re-run: node build.mjs
 *  Built ${new Date().toISOString()}
 */\n\n`;

async function concat(dir, ext) {
  const full = join(root, dir);
  const files = (await readdir(full)).filter((f) => f.endsWith(ext)).sort();
  const parts = [];
  for (const file of files) {
    parts.push(await readFile(join(full, file), "utf8"));
  }
  return { files, body: parts.join("\n") };
}

async function buildPreview() {
  const dir = join(root, "blocks");
  const files = (await readdir(dir))
    .filter((f) => f.endsWith(".html") && f !== "00-head.html")
    .sort();

  const sections = [];
  for (const file of files) {
    sections.push(await readFile(join(dir, file), "utf8"));
  }

  // The head block's CDN <link>/<script> are replaced with local paths so the
  // preview reflects uncommitted work instead of whatever is live on jsDelivr.
  const head = (await readFile(join(dir, "00-head.html"), "utf8"))
    .replace(
      /<link\s+rel="stylesheet"[\s\S]*?\/>/,
      '<link rel="stylesheet" href="dist/sirwade.css" />',
    )
    .replace(
      /<script\s+defer[\s\S]*?><\/script>/,
      '<script defer src="dist/sirwade.js"></script>',
    );

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Sir Wade — homepage preview</title>
<!-- GENERATED by build.mjs from blocks/*.html — do not edit directly. -->
<style>body{margin:0;background:#fff}</style>
${head}
</head>
<body>
${sections.join("\n")}
</body>
</html>
`;
}

const css = await concat("src/css", ".css");
const js = await concat("src/js", ".js");

await writeFile(
  join(root, "dist/sirwade.css"),
  banner("CSS") + css.body,
  "utf8",
);
await writeFile(join(root, "dist/sirwade.js"), banner("JS") + js.body, "utf8");
await writeFile(join(root, "preview.html"), await buildPreview(), "utf8");

console.log(`dist/sirwade.css  ← ${css.files.length} files`);
console.log(`dist/sirwade.js   ← ${js.files.length} files`);
console.log(`preview.html      ← blocks/*.html`);
